import Image from 'next/image';
import Link from 'next/link';
import {Phone,Sparkles,MessageCircle,Brain,Heart,Activity,Hand,Palette,Sun,Club,Calculator,Monitor,MapPin,Clock,Quote,Check} from 'lucide-react';
import type {Content,Contacts,Photo,Service,Specialist} from '@/lib/types';
import {photoUrl,telephone} from '@/lib/content';
const icons={speech:MessageCircle,brain:Brain,heart:Heart,activity:Activity,hands:Hand,palette:Palette,sun:Sun,chess:Club,math:Calculator,computer:Monitor};
export function Icon({name,size=28}:{name:string;size?:number}){const Component=icons[name as keyof typeof icons]||Sparkles;return <Component size={size} strokeWidth={1.5}/>}
export function BookingCTA({contacts,label='Записаться по телефону',secondary=false}:{contacts:Contacts;label?:string;secondary?:boolean}){return <a className={secondary?'button secondary':'button primary'} href={telephone(contacts.phone)}><Phone size={18}/>{label}</a>}
export function PhotoFrame({photo,fallback='/images/hero-lesson.jpg',alt,className='',priority=false}:{photo?:Photo;fallback?:string;alt:string;className?:string;priority?:boolean}){const src=photoUrl(photo)||fallback;return <div className={`photo-frame ${className}`}>{src?<Image src={src} alt={photo?.alt||alt} fill sizes="(max-width: 760px) 100vw, 50vw" priority={priority}/>:<div className="photo-empty"><Sparkles size={46}/><span>Знакомство начинается здесь</span></div>}</div>}
export function ServiceCard({service,index=0}:{service:Service;index?:number}){return <Link href={`/services#${service.slug}`} className={`service-card tone-${index%3}`}><span className="service-icon"><Icon name={service.icon}/></span><span className="service-age">{service.age}</span><h3>{service.title}</h3><p>{service.shortDescription}</p><div className="service-bottom"><span>{service.showPrice&&service.price?`${service.price.toLocaleString('ru-RU')} ₽`:'Стоимость по телефону'}</span><span>{service.duration} минут</span></div></Link>}
export function SpecialistCard({specialist,index=0}:{specialist:Specialist;index?:number}){const src=photoUrl(specialist.photo);return <Link className={`specialist-card ${specialist.isDemo?"is-demo":""}`} href={`/specialists#${specialist._id}`}><div className={`specialist-photo tone-${index%3}`}>{src?<Image src={src} alt={`${specialist.firstName} ${specialist.lastName}`} fill sizes="(max-width: 760px) 100vw, 33vw"/>:<><span className="profile-symbol"><Icon name={['speech','brain','heart','activity'][index%4]} size={32}/></span><span className="portrait-caption">Профиль готовится</span></>}</div><div className="specialist-copy"><span className="eyebrow">{specialist.position}</span><h3>{specialist.firstName} {specialist.lastName}</h3><p>{specialist.isDemo?'Информация о специалисте готовится':specialist.about}</p>{specialist.isDemo&&<span className="demo-tag">Пример карточки</span>}</div></Link>}
export function SectionHeading({eyebrow,title,description,link}:{eyebrow:string;title:string;description?:string;link?:[string,string]}){return <div className="section-heading"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2>{description&&<p className="section-description">{description}</p>}</div>{link&&<Link href={link[0]} className="text-link">{link[1]}</Link>}</div>}
export function CTASection({contacts}:{contacts:Contacts}){return <section className="wrap cta"><div><span className="eyebrow">Начнём со знакомства</span><h2>Не знаете, какой<br/>специалист нужен?</h2><p>{contacts.bookingText}</p></div><div className="cta-action"><a className="cta-number" href={telephone(contacts.phone)}>{contacts.phone}</a><BookingCTA contacts={contacts} label="Позвонить нам"/><small>Запись на занятия — по телефону</small></div></section>}
export function ContactSection({contacts}:{contacts:Contacts}){const embed=contacts.mapEmbedUrl;const allowed=embed&&/^https:\/\/yandex\.(ru|com)\/map-widget\//.test(embed);return <section className="wrap section" id="contacts"><SectionHeading eyebrow="Всегда рядом" title="Приходите знакомиться"/><div className="contacts-grid"><div className="contact-details"><div><MapPin/><span><strong>Наш адрес</strong><p>{contacts.address}</p></span></div><div><Phone/><span><strong>Позвоните нам</strong><a className="contact-number" href={telephone(contacts.phone)}>{contacts.phone}</a><p>Поможем выбрать направление и время</p></span></div><div><Clock/><span><strong>Часы работы</strong><p>{contacts.hours}</p></span></div><div className="socials">{contacts.vk&&<a href={contacts.vk} target="_blank" rel="noopener noreferrer">ВКонтакте</a>}{contacts.max&&<a href={contacts.max} target="_blank" rel="noopener noreferrer">МАКС</a>}{!contacts.vk&&!contacts.max&&<p>Ссылки на наши сообщества скоро появятся</p>}</div></div><div className="map-panel">{allowed?<iframe src={embed} title="Адрес центра на Яндекс Картах" loading="lazy" referrerPolicy="no-referrer-when-downgrade"/>:<><MapPin size={42} strokeWidth={1.3}/><h3>Солнечногорск</h3><p>ул. Пролетарская, 1/1</p><a className="button secondary" href={`https://yandex.ru/maps/?text=${encodeURIComponent(contacts.address)}`} target="_blank" rel="noopener noreferrer">Открыть Яндекс Карты</a></>}</div></div></section>}
export function Reviews({data}:{data:Content}){if(!data.reviews.some(review=>!review.isDemo))return <div className="reviews-pending"><p>Здесь появятся отзывы родителей.</p><span>Мы опубликуем их с согласия семей. А пока будем рады личному знакомству.</span></div>;return <div className="review-grid">{data.reviews.filter(review=>!review.isDemo).map(review=><article className="review-card" key={review._id}><Quote size={32} strokeWidth={1.2}/><p>{review.text}</p><div>{photoUrl(review.photo)&&<span className="review-avatar"><Image src={photoUrl(review.photo)!} alt={review.name} fill sizes="42px"/></span>}<strong>{review.name}</strong>{review.date&&<time dateTime={review.date}>{new Date(review.date).toLocaleDateString('ru-RU')}</time>}{review.isDemo&&<span className="demo-tag">Образец · не реальный отзыв</span>}</div></article>)}</div>}
export function Footer({contacts}:{contacts:Contacts}){return <footer><div className="wrap footer-main"><Link className="brand" href="/"><Sparkles size={34}/><span>Созвездие речи<small>У каждого свой путь. Мы рядом.</small></span></Link><div><a href={telephone(contacts.phone)}>{contacts.phone}</a><p>{contacts.address}</p></div><Link href="/vacancies">Стать частью команды</Link></div><div className="wrap footer-bottom"><span>© {new Date().getFullYear()} Созвездие речи</span><span>Информация о занятиях и стоимости уточняется при записи.</span></div></footer>}
export function WhyUs(){return <section className="why-section"><div className="wrap section"><SectionHeading eyebrow="Внимание к каждому" title="Не торопим. Поддерживаем. Помогаем."/><div className="why-grid">{[['Индивидуальный подход','Учитываем возраст, особенности и темп ребёнка.'],['Комплексная поддержка','Смотрим на развитие в целом и подбираем нужные направления.'],['На одной стороне с родителями','Обсуждаем цели и помогаем продолжать работу дома.'],['Профессиональный подход','Опираемся на подготовку специалистов и понятный план занятий.']].map(([title,text],i)=><div key={title}><span className="why-number">0{i+1}</span><h3>{title}</h3><p>{text}</p></div>)}</div></div></section>}
export function Values({values}:{values:string[]}){return <div className="values">{values.map(value=><span key={value}><Check size={18}/>{value}</span>)}</div>}
