'use client';
import Link from 'next/link';
import {BrandMark,HeaderConstellation} from './BrandMotif';
import {useState,useEffect,useRef} from 'react';
import {usePathname} from 'next/navigation';
import {Menu,X,Phone,MapPin} from 'lucide-react';
import {telephone} from '@/lib/phone';
export const navigation=[['/','Главная'],['/services','Услуги'],['/specialists','Специалисты'],['/about','О центре'],['/gallery','Галерея'],['/reviews','Отзывы'],['/vacancies','Вакансии'],['/contacts','Контакты']];
export function Header({phone,address}:{phone:string;address:string}){const [open,setOpen]=useState(false);const path=usePathname();const toggle=useRef<HTMLButtonElement>(null);useEffect(()=>{if(!open)return;const handler=(event:KeyboardEvent)=>{if(event.key==='Escape'){setOpen(false);toggle.current?.focus();}};document.addEventListener('keydown',handler);return ()=>document.removeEventListener('keydown',handler);},[open]);return <header><HeaderConstellation/><div className="topline"><span><MapPin size={14}/> {address}</span><span>Для детей от 2 лет и взрослых</span></div><div className="header-main wrap"><Link href="/" className="brand" aria-label="Созвездие речи — главная"><span className="brand-icon"><BrandMark/></span><span>Созвездие речи<small>Центр развития и поддержки</small></span></Link><nav id="site-navigation" aria-label="Основная навигация" className={open?'navigation open':'navigation'}>{navigation.map(([href,label])=><Link key={href} href={href} aria-current={path===href?'page':undefined} onClick={()=>setOpen(false)}>{label}</Link>)}</nav><a className="header-phone" href={telephone(phone)}><Phone size={16}/>{phone}</a><button ref={toggle} aria-controls="site-navigation" className="menu-toggle" onClick={()=>setOpen(!open)} aria-expanded={open} aria-label={open?'Закрыть меню':'Открыть меню'}>{open?<X/>:<Menu/>}</button></div></header>}
