import {defineType,defineField} from 'sanity';
const text=(name:string,title:string,multiline=false)=>defineField({name,title,type:multiline?'text':'string'});
const flag=(name:string,title:string,value=true)=>defineField({name,title,type:'boolean',initialValue:value});
const order=defineField({name:'order',title:'Порядок отображения',type:'number',initialValue:0});
const photoFields=[defineField({name:'alt',title:'Описание фотографии',type:'string'}),defineField({name:'localPath',title:'Путь к локальному фото',type:'string',description:'Например: /images/center.jpg. Обычно достаточно загрузить фотографию выше.'})];
const photo=(name:string,title:string)=>defineField({name,title,type:'image',options:{hotspot:true},fields:photoFields});
const photoArray=(name:string,title:string)=>defineField({name,title,type:'array',of:[{type:'image',options:{hotspot:true},fields:photoFields}]});
const list=(name:string,title:string)=>defineField({name,title,type:'array',of:[{type:'string'}]});
export const schemaTypes=[
defineType({name:'specialist',title:'Специалисты',type:'document',fields:[text('firstName','Имя'),text('lastName','Фамилия'),photo('photo','Фотография'),text('position','Должность'),text('specialization','Специализация',true),text('experience','Опыт работы'),text('education','Образование',true),text('qualification','Квалификация',true),text('about','О специалисте',true),list('directions','Направления работы'),photoArray('certificates','Сертификаты'),photoArray('diplomas','Дипломы'),order,flag('visible','Показывать'),flag('isDemo','Это пример, а не реальные данные',false)],preview:{select:{title:'firstName',subtitle:'position',media:'photo'}}}),
defineType({name:'service',title:'Услуги',type:'document',fields:[text('title','Название услуги'),defineField({name:'slug',title:'Адрес раздела',type:'string',description:'Латинские буквы, цифры и дефисы. Например: logoped',validation:r=>r.required().regex(/^[a-z0-9-]+$/)}),text('shortDescription','Краткое описание',true),text('description','Полное описание',true),photo('photo','Фото'),defineField({name:'icon',title:'Иконка',type:'string',options:{list:[{title:'Речь',value:'speech'},{title:'Мышление',value:'brain'},{title:'Эмоции',value:'heart'},{title:'Движение',value:'activity'},{title:'Массаж',value:'hands'},{title:'Творчество',value:'palette'},{title:'Забота',value:'sun'},{title:'Шахматы',value:'chess'},{title:'Математика',value:'math'},{title:'Компьютер',value:'computer'}]}}),text('age','Возраст'),defineField({name:'duration',title:'Продолжительность, минуты',type:'number',initialValue:45,validation:r=>r.min(1)}),defineField({name:'price',title:'Стоимость, рубли',type:'number',validation:r=>r.min(0)}),flag('showPrice','Показывать цену'),defineField({name:'format',title:'Формат занятия',type:'string',options:{list:['Индивидуально','В группе']},initialValue:'Индивидуально'}),order,flag('active','Активна')]}),
defineType({name:'review',title:'Отзывы',type:'document',fields:[text('name','Имя'),text('text','Текст отзыва',true),photo('photo','Фото'),defineField({name:'date',title:'Дата',type:'date'}),order,flag('visible','Показывать'),flag('isDemo','Это пример, а не реальный отзыв',false)]}),
defineType({name:'vacancy',title:'Вакансии',type:'document',fields:[text('title','Название вакансии'),text('description','Описание',true),list('requirements','Требования'),flag('active','Активна'),order]}),
defineType({name:'about',title:'О центре',type:'document',fields:[text('title','Заголовок'),text('history','История центра',true),text('mission','Миссия',true),list('values','Ценности'),text('description','Описание',true),photo('photo','Фото центра'),photo('heroPhoto','Главное фото на главной странице'),photoArray('gallery','Галерея центра'),text('subscriptions','Абонементы',true)]}),
defineType({name:'contacts',title:'Контакты',type:'document',fields:[text('phone','Телефон'),text('address','Адрес',true),defineField({name:'vk',title:'ВКонтакте',type:'url',validation:r=>r.uri({scheme:['https']})}),defineField({name:'max',title:'МАКС',type:'url',validation:r=>r.uri({scheme:['https']})}),text('hours','Часы работы'),text('bookingText','Текст о записи',true),defineField({name:'mapEmbedUrl',title:'Яндекс Карты — ссылка для встраивания',type:'url',description:'Ссылка вида https://yandex.ru/map-widget/... из кода «Поделиться → Вставить на сайт».',validation:r=>r.custom(value=>!value||/^https:\/\/yandex\.(ru|com)\/map-widget\//.test(value)?true:'Укажите ссылку Яндекс Карт для встраивания')})]}),
defineType({name:'galleryItem',title:'Галерея',type:'document',fields:[photo('photo','Фото'),text('caption','Подпись'),order],preview:{select:{title:'caption',media:'photo'}}})
];
